name: Backend Notify

on:
  workflow_run:
    workflows: ["Guidein Backend End CI/CD"]  # This MUST exactly match the name of your backend CI/CD workflow
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run your Build or Deployment
        run: echo "✅ Backend Build or Deploy Successful"

      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ✅ Backend Build Success - ${{ github.repository }}
          body: |
            🎉 Backend CI/CD Job completed successfully!
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}
          to: saikumartanakala2001@gmail.com, inti.vvsn@gmail.com, devalankaveerababu222@gmail.com
          from: GitHub Actions <s4resh9o@gmail.com>
